# Generated by Django 6.0.1 on 2026-01-28 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('capacity_kwh', models.FloatField(help_text='Capacity in kWh')),
                ('voltage', models.FloatField(help_text='Nominal voltage')),
                ('chemistry', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('max_power_watts', models.FloatField(help_text='Maximum input power in Watts')),
                ('efficiency', models.FloatField(help_text='Efficiency percentage')),
                ('is_hybrid', models.BooleanField(default=False, help_text='Can handle batteries?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('power_watts', models.FloatField(help_text='Rated power in Watts')),
                ('voltage_oc', models.FloatField(help_text='Open circuit voltage (Voc)')),
                ('current_sc', models.FloatField(help_text='Short circuit current (Isc)')),
                ('efficiency', models.FloatField(blank=True, help_text='Efficiency percentage', null=True)),
                ('length_mm', models.FloatField(blank=True, null=True)),
                ('width_mm', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBatteryBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design.battery')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectInverterBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design.inverter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPanelArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('orientation', models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape')], default='Portrait', max_length=20)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design.panel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tilt_angle', models.FloatField(default=0.0, help_text='Panel tilt angle in degrees')),
                ('azimuth_angle', models.FloatField(default=180.0, help_text='Panel azimuth angle (180=South)')),
                ('electricity_rate', models.FloatField(default=0.15, help_text='Cost per kWh')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='design.project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('generated_content', models.TextField(help_text='JSON or text content of the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='design.project')),
            ],
        ),
    ]
