# Generated by Django 6.0.1 on 2026-01-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='current_sc',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='power_watts',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='voltage_oc',
        ),
        migrations.AddField(
            model_name='panel',
            name='impp',
            field=models.FloatField(default=0.0, help_text='Current at Maximum Power (Impp) in Amps'),
        ),
        migrations.AddField(
            model_name='panel',
            name='isc',
            field=models.FloatField(default=0.0, help_text='Short Circuit Current (Isc) in Amps'),
        ),
        migrations.AddField(
            model_name='panel',
            name='pmax',
            field=models.FloatField(default=0.0, help_text='Maximum Power (Pmax) in Watts'),
        ),
        migrations.AddField(
            model_name='panel',
            name='thickness_mm',
            field=models.FloatField(blank=True, help_text='Thickness/Depth in mm', null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='vmpp',
            field=models.FloatField(default=0.0, help_text='Voltage at Maximum Power (Vmpp) in Volts'),
        ),
        migrations.AddField(
            model_name='panel',
            name='voc',
            field=models.FloatField(default=0.0, help_text='Open Circuit Voltage (Voc) in Volts'),
        ),
        migrations.AddField(
            model_name='panel',
            name='weight_kg',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='efficiency',
            field=models.FloatField(default=0.0, help_text='Module Efficiency (%)'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='length_mm',
            field=models.FloatField(default=0.0, help_text='Length in mm'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='width_mm',
            field=models.FloatField(default=0.0, help_text='Width in mm'),
        ),
    ]
