# Generated by Django 6.0.1 on 2026-01-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_remove_panel_current_sc_remove_panel_power_watts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inverter',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='inverter',
            name='is_hybrid',
        ),
        migrations.RemoveField(
            model_name='inverter',
            name='max_power_watts',
        ),
        migrations.AddField(
            model_name='inverter',
            name='ac_efficiency',
            field=models.FloatField(default=0.0, help_text='AC Efficiency (%)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='ac_input_frequency',
            field=models.FloatField(default=50.0, help_text='Input frequency (Hz)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='ac_max_voltage',
            field=models.FloatField(default=280.0, help_text='Max input voltage (V)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='ac_nominal_voltage',
            field=models.FloatField(default=230.0, help_text='Nominal input voltage (V)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='battery_voltage_nominal',
            field=models.CharField(choices=[('24VDC', '24VDC'), ('48VDC', '48VDC'), ('24VDC/48VDC', '24VDC/48VDC')], default='48VDC', max_length=20),
        ),
        migrations.AddField(
            model_name='inverter',
            name='depth_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inverter',
            name='height_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inverter',
            name='inverter_type',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Offgrid', 'Offgrid')], default='Offgrid', max_length=20),
        ),
        migrations.AddField(
            model_name='inverter',
            name='max_charge_current_total',
            field=models.FloatField(default=0.0, help_text='Max charge current (A)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='motor_start_hp',
            field=models.FloatField(default=0.0, help_text='Capable of starting electric motor (HP)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='pv_dc_voltage_nominal',
            field=models.FloatField(default=0.0, help_text='DC voltage / MPPT Range (V)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='pv_max_charge_current',
            field=models.FloatField(default=0.0, help_text='Maximum PV Charge current (A)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='pv_max_efficiency',
            field=models.FloatField(default=0.0, help_text='Maximum efficiency (%)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='pv_max_input_voltage',
            field=models.FloatField(default=0.0, help_text='Maximum solar input voltage (V)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='pv_max_power_watts',
            field=models.FloatField(default=0.0, help_text='Maximum PV array power (W)'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='rated_power_watts',
            field=models.FloatField(default=0.0, help_text='Rated power in Watts'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='surge_rating_watts',
            field=models.FloatField(default=0.0, help_text='Surge rating in Watts'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='width_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='projectbatterybank',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectinverterblock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectpanelarray',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
