# Generated by Django 6.0.1 on 2026-01-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_remove_inverter_efficiency_remove_inverter_is_hybrid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battery',
            name='capacity_kwh',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='voltage',
        ),
        migrations.AddField(
            model_name='battery',
            name='depth_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='battery',
            name='end_of_discharge_voltage',
            field=models.FloatField(default=0.0, help_text='End of discharge voltage (V)'),
        ),
        migrations.AddField(
            model_name='battery',
            name='height_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='battery',
            name='life_cycles',
            field=models.PositiveIntegerField(default=0, help_text='Life Cycles (e.g. 6000)'),
        ),
        migrations.AddField(
            model_name='battery',
            name='nominal_capacity_ah',
            field=models.FloatField(default=0.0, help_text='Nominal capacity (Ah)'),
        ),
        migrations.AddField(
            model_name='battery',
            name='nominal_energy_wh',
            field=models.FloatField(default=0.0, help_text='Nominal energy (Wh)'),
        ),
        migrations.AddField(
            model_name='battery',
            name='nominal_voltage',
            field=models.FloatField(default=0.0, help_text='Nominal voltage (V)'),
        ),
        migrations.AddField(
            model_name='battery',
            name='rec_charge_current',
            field=models.FloatField(default=0.0, help_text='Recommended charge current (A)'),
        ),
        migrations.AddField(
            model_name='battery',
            name='rec_charge_voltage',
            field=models.FloatField(default=0.0, help_text='Recommended charge voltage (V)'),
        ),
        migrations.AddField(
            model_name='battery',
            name='warranty_years',
            field=models.PositiveIntegerField(default=0, help_text='Warranty in years'),
        ),
        migrations.AddField(
            model_name='battery',
            name='weight_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='battery',
            name='width_mm',
            field=models.FloatField(default=0.0),
        ),
    ]
