# Generated by Django 6.0.1 on 2026-01-29 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_remove_battery_capacity_kwh_remove_battery_voltage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_index', models.PositiveIntegerField(help_text='1 for most recent, 6 for oldest')),
                ('month_name', models.CharField(help_text='e.g., January', max_length=20)),
                ('kwh_value', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='design.project')),
            ],
            options={
                'ordering': ['month_index'],
            },
        ),
    ]
