# Generated by Django 6.0.1 on 2026-01-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_monthlyconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='autonomy_hours',
            field=models.FloatField(default=8.0, help_text='Desired battery backup hours (e.g. 8.0)'),
        ),
    ]
