# Generated by Django 6.0.1 on 2026-01-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_projectsettings_autonomy_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='location_name',
            field=models.CharField(blank=True, help_text='Automatically determined from coordinates', max_length=255),
        ),
    ]
