# Generated by Django 6.0.1 on 2026-01-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_projectsettings_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='batteries/'),
        ),
        migrations.AddField(
            model_name='inverter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inverters/'),
        ),
        migrations.AddField(
            model_name='panel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='panels/'),
        ),
    ]
