# Generated by Django 6.0.1 on 2026-01-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_battery_image_inverter_image_panel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='pv_max_input_current',
            field=models.FloatField(default=0.0, help_text='Maximum PV input current (A)'),
        ),
        migrations.AddField(
            model_name='panel',
            name='temp_coeff_pmax',
            field=models.FloatField(blank=True, default=-0.4, help_text='Temp. Coeff of Pmax (%/°C)', null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='temp_coeff_voc',
            field=models.FloatField(blank=True, default=-0.3, help_text='Temp. Coeff of Voc (%/°C)', null=True),
        ),
    ]
