# Generated by Django 6.0.1 on 2026-01-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_inverter_pv_max_input_current_panel_temp_coeff_pmax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='hsp_min',
            field=models.FloatField(default=4.5, help_text='Minimum Peak Sun Hours (HSP) for sizing'),
        ),
    ]
